### ISSUE TITLE
Resurrected After 7 Years

### ISSUE THREAD

**Issue by joinr** [joshpeterson/nash-clojure#1]
Josh,

Somehow your old blog post made it into the r/clojure subreddit (I don't know if you were the submitter; if so then some of this is duplicated there and I apologize for spamming).

I was curious to explore the scaling issues you brought up (after reading the post 7 years later :) ), and ended up optimizing your legacy code a bit.  For pedagogical interest, there's a fork at https://github.com/joinr/nash-clojure/, with some notes in the readme explaining what I did and my observations.  The [fast](https://github.com/joinr/nash-clojure/blob/master/src/nash_clojure/fast.clj) ns has a specific set of changes that modify the original representation to a bit more efficient one (while trying to retain some of the high level appeal).  Improved mechanical sympathy bore fruit in scaling as well (on my machine at least), where things are much closer to linear than I expected (I typically observe a soft limit of about 4x with significant diminishing returns afterward in normal allocation-heavy independent workloads typical in clojure).

Just wanted to say thanks for posting; I enjoyed reading your code and exploring scaling further and learning something in the process.

**Comment by joshpeterson** [comment]
Wow, I've not thought about this repo for a while! Thanks for checking into it an improving my code. I didn't know much about Clojure at the time (and still don't), but your description of the issues in the code makes a lot of sense.

I'm glad you found it interesting. I certainly this this is a fun problem.
